### ISSUE TITLE
[Question] Service-configuration

### ISSUE THREAD

**Issue by abashinyan** [lirbank/meteor-accounts-merge#4] opened 2014-04-11 09:46 UTC
Hi, 
You need to add: 
```meteor add service-configuration```
 as well as accounts-facebook accounts-google accounts-twitter?

Without it not working

**Comment by lirbank** [comment] 2015-02-17 00:05
Can't reproduce this one anymore, closing.

**Closed by lirbank** 2015-02-17 00:05 UTC
Labels: bug
